local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<leader>a", mark.add_file, { desc = "[A]dd current file to harpoon" })
vim.keymap.set("n", "<C-e>", ui.toggle_quick_menu, { desc = "Toggle the quick menu" })

vim.keymap.set("n", "<C-j>", function()
  ui.nav_file(1)
end, { desc = "File nav 1" })
vim.keymap.set("n", "<C-k>", function()
  ui.nav_file(2)
end, { desc = "File nav 2" })
vim.keymap.set("n", "<C-n>", function()
  ui.nav_file(3)
end, { desc = "File nav 3" })
vim.keymap.set("n", "<C-m>", function()
  ui.nav_file(4)
end, { desc = "File nav 4" })
